### ISSUE TITLE
fibonacci

### ISSUE THREAD

**Issue by azole** [ikl258794613/node.js-MFEE16-03#1]
https://github.com/ikl258794613/node.js-MFEE16-03/blob/437f768b3ac42f68e6f372b69553572350785076/basic/fibonacci.js

差不多了，可以有更漂亮的寫法，想不想挑戰看看？想試試看的話，可以去查一下  memoization 跟 curry 這兩個關鍵字。

**Comment by ikl258794613** [comment]
我查看看
