### ISSUE TITLE
resolve 回傳的資訊建議

### ISSUE THREAD

**Issue by azole** [ikl258794613/node.js-MFEE16-03#2]
https://github.com/ikl258794613/node.js-MFEE16-03/blob/078e36817f0a32218d33aeee2b33b573748f2320/basic/xhr_promise.html#L31

通常這裡會回傳 xhr 拿到的結果，例如 `xhr.responseText`，但這個看情景設計。

**Comment by ikl258794613** [comment]
有注意到回傳了sleep bug 想說怪怪的
